#' Convert to MediaWiki Markup
#'
#' Format for converting from R Markdown to MediaWiki Markup.
#'
#' @param keep_md Keep the markdown file generated by knitting.
#'
#' @seealso
#' \href{https://www.mediawiki.org/wiki/Help:Formatting}{MediaWiki markup
#' documentation}
#'
#' @return R Markdown output format to pass to \code{\link[rmarkdown]{render}}
#' @export
mediawiki_document = function(keep_md = FALSE) {
  rmarkdown::output_format(
    knitr  = rmarkdown::knitr_options(opts_chunk = list(dev = 'png')),
    pandoc = rmarkdown::pandoc_options(to = "mediawiki"),
    keep_md = keep_md,
    clean_supporting = TRUE
  )
}

